<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="Employee List.aspx.cs" Inherits="Employee_Employee_List" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" Runat="Server">

    <h2><%: Title %>.</h2>
    <p class="text-danger">
        <asp:Literal runat="server" ID="ErrorMessage" />
        <asp:Label ID="SuccessLabel" runat="server" Display="Dynamic" ></asp:Label>
    </p>
    <div class="form-horizontal">
        <h4>Employee Listing.</h4>

        <asp:SqlDataSource ID="EmployeeData" runat="server" ConnectionString="<%$ ConnectionStrings:DependentConnectionString %>" SelectCommand="SELECT * FROM [Employee] ORDER BY [EmpLastName]"></asp:SqlDataSource>
        <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#E7E7FF" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="EmpSSN" DataSourceID="EmployeeData" HorizontalAlign="Center" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            <AlternatingRowStyle BackColor="#F7F7F7" />
            <Columns>
                <asp:CommandField ShowSelectButton="True" />
                <asp:BoundField DataField="EmpId" HeaderText="EmpId" SortExpression="EmpId" />
                <asp:BoundField DataField="EmpFirstName" HeaderText="EmpFirstName" SortExpression="EmpFirstName" />
                <asp:BoundField DataField="EmpLastName" HeaderText="EmpLastName" SortExpression="EmpLastName" />
                <asp:BoundField DataField="EmpSSN" HeaderText="EmpSSN" ReadOnly="True" SortExpression="EmpSSN" />
                <asp:BoundField DataField="EmpStartDate" HeaderText="EmpStartDate" SortExpression="EmpStartDate" />
                <asp:CheckBoxField DataField="EmpActive" HeaderText="EmpActive" SortExpression="EmpActive" />
            </Columns>
            <FooterStyle BackColor="#B5C7DE" ForeColor="#4A3C8C" />
            <HeaderStyle BackColor="#4A3C8C" Font-Bold="True" ForeColor="#F7F7F7" />
            <PagerStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" HorizontalAlign="Right" />
            <RowStyle BackColor="#E7E7FF" ForeColor="#4A3C8C" />
            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="#F7F7F7" />
            <SortedAscendingCellStyle BackColor="#F4F4FD" />
            <SortedAscendingHeaderStyle BackColor="#5A4C9D" />
            <SortedDescendingCellStyle BackColor="#D8D8F0" />
            <SortedDescendingHeaderStyle BackColor="#3E3277" />
        </asp:GridView>

        <hr />





    </div>

</asp:Content>

